### PR TITLE
Improvements on the way the string is tokenized

### LINKED ISSUE #12: Improvements on the way the string is tokenized.
Currently, the way the string input is tokenized is just using a simple split method. 

Perhaps using a better tokenize library would give better results. For example [here](https://www.npmjs.com/package/@stdlib/nlp-tokenize)

### PR DESCRIPTION
**Pull request by Prashriya**
Closes #12 
Added tokenize library: @stdlib/nlp-tokenize

### CODE REVIEW

**Comment by JianLoong** [comment]
Hello,

Please note that this PR will break the functionality of the word cloud generation. Have you tested the functionality on your end?

Regards,

Jian

**Comment by Prashriya** [comment]
There were no problems on my side. 
Can you point how and where the functionality will be broken?

**Comment by JianLoong** [comment]
This is the error I am getting. 

image

Have you tried running the project in incognito mode? Or try to hard refresh as web workers tend to be cached.  

Anyways, I will just mark it as ``accepted``, so you don't have to work on it if you don't want to. 👍 

Edited - For grammatical mistakes

**Comment by Prashriya** [comment]
@JianLoong  Could you please check the fix? 
I have attached the output generated on my machine in incognito mode after the fix.
cloud_generator

Also, could you add "hacktoberfest-accepted" label instead of "hacktober-accepted"?

**Comment by JianLoong** [comment]
Thank you. I have corrected the labels. Hopefully it is in time.

**Pull request merged**
