### PR TITLE
consistent names and ids

### PR DESCRIPTION
**Pull request by JanitaRiyaz**
- [x] fix names and ids of HTML elements

### CODE REVIEW

**Comment by JianLoong** [comment]
Hi,

Please note that the **checkboxes** should also be fixed.

image

So, when I click on the text itself, the specific checkbox should be ticked as well. Very similar to what is done [here](https://getbootstrap.com/docs/5.0/forms/checks-radios/)

Refers to #3

**Comment by JanitaRiyaz** [comment]
ok... wait shortly...i'll come with solution😊

**Comment by JanitaRiyaz** [comment]
I tried my best to resolve this but unable to solve. Plz accept my earlier solution and merge it.

**Comment by JianLoong** [comment]
Hi, I will mark this is accepted and merge this PR. 

Thank you.

**Pull request merged**
